############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Research"
url = "research/"
weight = 2

[[main]]
name = "Teaching"
url = "teaching/"
weight = 3

[[main]]
name = "Media"
url = "media/"
weight = 4

[[main]]
name = "CV"
url = "/cv_meza-cesar.pdf"
weight = 5


#[[main]]
#name = "Elements"
#url = "elements/"
#weight = 3

#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "blog/"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "contact/"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "authors/"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "categories/"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "404/"


# footer menu
#[[footer]]
#name = "About"
#url = "about/"
#weight = 1

#[[footer]]
#name = "Elements"
#url = "elements/"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3
